name: 'covid data analysis'
description: 'Calculate average and rolling window info from JH covid data.'
inputs:
  path: 
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -v ${{ inputs.path }}:/data