name: covid-workflow

on: [push]
  # schedule:
  #   - cron: "*/2 * * * *"

jobs:
  covid-workflow:
    name: brazilian covid time series
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cloning CSSE repo
        run: git clone https://github.com/CSSEGISandData/COVID-19.git

      - name: Covid data analysis
        uses: ./

      - name: Files produced
        run: ls /home/runner/work/covid-github-actions-test/covid-github-actions-test

      - name: Push back
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes
          file_pattern: /home/runner/work/covid-github-actions-test/covid-github-actions-test/*.png

