name: Covid-workflow

on:   
  schedule:
    - cron: "*/2 * * * *"

jobs:
  covid-workflow:
    name: brazilian covid time series
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # checkout john hopkins covid data repo
      - name: Checkout CSSE
        uses: actions/checkout@v2
        with:
          repository: CSSEGISandData/COVID-19
